name: TestFlow API CI

on:
    push:
        branches:
         - main
    pull_request:
        branches:
         - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v3
            - name: Build Docker image
              run: |
                docker build -t testflow-api:${{ github.sha }} .
                